name: Pull Request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  node:
    uses: nasa-gcn/.github/.github/workflows/node.yml@main



  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev
  

      - name: Check Python version
        run: python -V

      - name: Pip Install
        run: pip install -r requirements.txt

      - name: Pytest
        run: pytest python
        shell: alpine.sh {0}

      - name: MyPy
        run: mypy python
        shell: alpine.sh {0}

      - name: Upload to Codecov.io
        uses: codecov/codecov-action@v3
