name: Pull Request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  node:
    uses: nasa-gcn/.github/.github/workflows/node.yml@main

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Run python build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: nikolaik/python-nodejs:python3.11-nodejs21
          options: |
            --platform linux/arm64
            --volume ${{ runner.temp }}/python:/python
            --volume ${{ github.workspace }}/../:/build
          run: |
            cd /build
            cd gcn.nasa.gov/
            pip install -r requirements.txt -t ./vendor

      - name: Pytest
        run: pytest python


      - name: MyPy
        run: mypy python
        shell: alpine.sh {0}

      - name: Upload to Codecov.io
        uses: codecov/codecov-action@v3
