name: Pull Request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  node:
    uses: nasa-gcn/.github/.github/workflows/node.yml@main
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Alpine Linux v3.15 for aarch64
        uses: jirutka/setup-alpine@v1
        with:
          arch: aarch64
          branch: v3.15

      - name: Run script inside Alpine chroot with aarch64 emulation
        run: uname -m
        shell: alpine.sh {0}


      - uses: actions/checkout@v4

      - uses: psf/black@stable

      - name: Setup Python 3.11
        run: apk add python3 py3-pip
        shell: alpine.sh --root {0}

      - name: Pip Install
        run: pip install -r requirements.txt
        shell: alpine.sh {0}

      - name: Pytest
        run: pytest python
        shell: alpine.sh {0}

      - name: MyPy
        run: mypy python
        shell: alpine.sh {0}

      - name: Upload to Codecov.io
        uses: codecov/codecov-action@v3
