name: Pull Request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  node:
    uses: nasa-gcn/.github/.github/workflows/node.yml@main



  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Make R library
        run: mkdir -p ${RUNNER_TEMP}/R-lib
  
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/grimbough/bioc-with-tinytex:devel-arm64
          options: |
            --platform linux/arm64
            --volume ${{ runner.temp }}/python:/python
            --volume ${{ github.workspace }}/../:/build
          run: |
            cd /build
            ls
            pip install -r requirements.txt

  

      - name: Check Python version
        run: python -V

      - name: Pip Install
        run: pip install -r requirements.txt

      - name: Pytest
        run: pytest python
        shell: alpine.sh {0}

      - name: MyPy
        run: mypy python
        shell: alpine.sh {0}

      - name: Upload to Codecov.io
        uses: codecov/codecov-action@v3
